apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    shard: 0
  name: redis-0
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP
