apiVersion: freelan.org/v1
kind: RedisCluster
metadata:
  name: cluster-3-2-no-disk
spec:
  instances: 3
  duplicates: 2
  cluster: false
  template:
    metadata:
      labels:
        app: redis-no-disk
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: "redis:3.2.0-alpine"
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
          - name: redis
            containerPort: 6379
            protocol: "TCP"
        volumeMounts:
          - name: "redis-conf"
            mountPath: "/etc/redis"
      volumes:
        - name: "redis-conf"
          configMap:
            name: "redis-conf-no-disk"
            items:
              - key: "redis.conf"
                path: "redis.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf-no-disk
data:
  redis.conf: |
    appendonly no
    save ""
    port 6379
